(define (problem food_reminder)
(:domain shr_domain)
(:objects
CallAction1 CallAction2 CallAction3 - CallAction
ReminderAction1 ReminderAction2 ReminderAction3 ReminderAction4 - ReminderAction
Msg1 Msg2 Msg3 Msg4 Msg5 Msg6 Msg7 - Msg
Time1 Time2 Time3 Time4 Time5 - Time
Person1 - Person
Landmark1 Landmark2 - Landmark
)
(:init
	(reminder_not_person_location_constraint ReminderAction4 Person1 Landmark2)
	(reminder_not_person_location_constraint ReminderAction3 Person1 Landmark2)
	(call_not_person_location_constraint CallAction2 Person1 Landmark2)
	(traversable Landmark1 Landmark2)
	(traversable Landmark2 Landmark1)
	(call_person_not_eating_food_constraint CallAction1 Person1)
	(current_time Time1)
	(MakeCall_enabled)
	(food_eaten_success)
	(next_time Time4 Time5)
	(next_time Time3 Time4)
	(next_time Time2 Time3)
	(next_time Time1 Time2)
	(GiveReminder_enabled)
	(reminder_blocks_call ReminderAction2 CallAction1)
	(reminder_blocks_call ReminderAction4 CallAction2)
	(DetectEatingFood_enabled)
	(DetectPerson_enabled)
	(reminder_person_not_eating_food_constraint ReminderAction4 Person1)
	(reminder_person_not_eating_food_constraint ReminderAction3 Person1)
	(reminder_person_not_eating_food_constraint ReminderAction2 Person1)
	(reminder_person_not_eating_food_constraint ReminderAction1 Person1)
	(robot_at Landmark1)
	(reminder_person_location_constraint ReminderAction2 Person1 Landmark2)
	(reminder_person_location_constraint ReminderAction1 Person1 Landmark2)
	(person_at Time1 Person1 Landmark2)
	(reminder_blocks_reminder ReminderAction1 ReminderAction2)
	(reminder_blocks_reminder ReminderAction3 ReminderAction4)
	(message_given_success Msg6)
	(message_given_success Msg5)
	(message_given_success Msg7)
	(valid_call_message CallAction1 Msg6)
	(valid_call_message CallAction2 Msg5)
	(valid_call_message CallAction3 Msg7)
	(valid_reminder_message ReminderAction1 Msg3)
	(valid_reminder_message ReminderAction2 Msg4)
	(valid_reminder_message ReminderAction3 Msg1)
	(valid_reminder_message ReminderAction4 Msg2)
	(unknown (person_at Time5 Person1 Landmark2))
	(unknown (person_at Time5 Person1 Landmark1))
	(unknown (person_at Time4 Person1 Landmark2))
	(unknown (person_at Time4 Person1 Landmark1))
	(unknown (person_at Time3 Person1 Landmark2))
	(unknown (person_at Time3 Person1 Landmark1))
	(unknown (person_at Time2 Person1 Landmark2))
	(unknown (person_at Time2 Person1 Landmark1))
	(oneof (person_at Time2 Person1 Landmark1) (person_at Time2 Person1 Landmark2))
	(oneof (person_at Time3 Person1 Landmark1) (person_at Time3 Person1 Landmark2))
	(oneof (person_at Time4 Person1 Landmark1) (person_at Time4 Person1 Landmark2))
	(oneof (person_at Time5 Person1 Landmark1) (person_at Time5 Person1 Landmark2))
)
(:goal
(success))
)
